// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQfNgi4rKpIOXdKCgSwVWLTWolzorP1Nk',
    appId: '1:862428239684:web:6e62ca83d8f00c1aeea911',
    messagingSenderId: '862428239684',
    projectId: 'pembersihkulkas-6f959',
    authDomain: 'pembersihkulkas-6f959.firebaseapp.com',
    databaseURL: 'https://pembersihkulkas-6f959-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pembersihkulkas-6f959.firebasestorage.app',
    measurementId: 'G-3WXE3NZ6QB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWPoGvdSL0lVJ3bjnreLrXpA6ENBiYQDk',
    appId: '1:862428239684:android:62968b409d69218feea911',
    messagingSenderId: '862428239684',
    projectId: 'pembersihkulkas-6f959',
    databaseURL: 'https://pembersihkulkas-6f959-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pembersihkulkas-6f959.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD91sj0fv2OM-5QifrnD_ilo4zO1xuuCDk',
    appId: '1:862428239684:ios:73e7a5316c4f0eb7eea911',
    messagingSenderId: '862428239684',
    projectId: 'pembersihkulkas-6f959',
    databaseURL: 'https://pembersihkulkas-6f959-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pembersihkulkas-6f959.firebasestorage.app',
    iosBundleId: 'com.example.pembersihKulkas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD91sj0fv2OM-5QifrnD_ilo4zO1xuuCDk',
    appId: '1:862428239684:ios:73e7a5316c4f0eb7eea911',
    messagingSenderId: '862428239684',
    projectId: 'pembersihkulkas-6f959',
    databaseURL: 'https://pembersihkulkas-6f959-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pembersihkulkas-6f959.firebasestorage.app',
    iosBundleId: 'com.example.pembersihKulkas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQfNgi4rKpIOXdKCgSwVWLTWolzorP1Nk',
    appId: '1:862428239684:web:35132e1478173e25eea911',
    messagingSenderId: '862428239684',
    projectId: 'pembersihkulkas-6f959',
    authDomain: 'pembersihkulkas-6f959.firebaseapp.com',
    databaseURL: 'https://pembersihkulkas-6f959-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pembersihkulkas-6f959.firebasestorage.app',
    measurementId: 'G-T0V2L8VWGV',
  );

}